# https://docs.microsoft.com/en-us/rest/api/resources/deployments/deployments_get

method: GET
url: https://management.azure.com/subscriptions/{{ azure.subscription }}/resourcegroups/{{ azure.resourceGroup }}/providers/Microsoft.Resources/deployments/{{ azure.deploymentName }}?api-version=2018-02-01
auth:
  tenant: {{ azure.tenant }}
  resource: https://management.azure.com/
  client: 04b07795-8ddb-461a-bbee-02f9e1bf7b46 # Azure CLI
secret: result.body.properties.correlationId
