values:
  request:
    auth:
      tenant: ( azure.tenant )
    path:
      subscriptionId: ( azure.subscription )
      resourceGroupName: ( azure.resourceGroup )
      deploymentName: {{ azure.deploymentName }}-{{ guid (datetime add="PT0S") }}

operations:
- message: Create or update resource group
  values:
    request:
      body:
        location: ( azure.location )
  request: apis/azure/ResourceGroups_CreateOrUpdate.yaml

- message: Create deployment
  values:
    request:
      body: 
        properties:
          mode: Incremental
          debugSetting:
            detailLevel: requestContent,responseContent
          template: {{> templates/201-web-app-sql-database/azuredeploy.json }}
          parameters: 
            sqlAdministratorLogin:
              value: azuresql
            sqlAdministratorLoginPassword:
              value: "{{ secret (guid provider="RNGCryptoServiceProvider") }}"
  request: apis/azure/Deployments_CreateOrUpdate.yaml
  catch:
    condition: ( result.status == `400` )
    output:
      failure: ( result.body.error )

- message: Monitoring deployment...
  condition: ( failure == null )
  request: apis/azure/Deployments_Get.yaml
  output:
    failure: ( result.body.properties.error )
    provisioningState: ( result.body.properties.provisioningState )
    deployment:
      outputResources: ( result.body.properties.outputResources )
      outputs: ( result.body.properties.outputs )
  repeat:
    condition: ( contains(['Accepted', 'Running'], provisioningState) )
    delay: PT15S
    timeout: PT38M
  catch:
    condition: ( result.status == `400` )
    output:
      failure: ( result.body.error )

- message: ( ['Failure ', failure.code] )
  condition: ( failure != null )
  throw: 
    message: ( failure.message )
    details: ( failure )

- message: Web app deployment sync
  values:
    request:
      path:
        name: ( deployment.outputs.siteName.value )
  operations:
  - message: Listing deployments
    request: apis/azure/WebApps_ListDeployments.yaml

  - message: Calling deploy hook
    values:
      request:
        body:
          format: basic
          url: "{{ app.sourcecontrol.repoUrl }}"          
    request: apis/scm/WebApps_Deploy.yaml

  - message: Listing deployments
    request: apis/azure/WebApps_ListDeployments.yaml

- message: Running database migration
  values:
    request:
      siteUri: ( join('', ['http://', deployment.outputs.siteUri.value.to_string(@)]) )
  request: apis/app/Blogs_Migrate.yaml

