# secrets - {{ secret azure.subscription }} {{ secret azure.tenant }}

operations:
- condition: (azure.tenant == null)
  output: {missing: {azure: {tenant: 'YOUR-TENANT-ID or --set azure.tenant=YOUR-TENANT-ID'}}}
- condition: (azure.subscription == null)
  output: {missing: {azure: {subscription: 'YOUR-SUBSCRIPTION-ID or --set azure.subscription=YOUR-SUBSCRIPTION-ID'}}}
- condition: (missing != null)
  throw: {message: The following must be provided by values.yaml in your working directory or be --set on the command line, details: (missing)}

- message: Create or update resource group
  request: ResourceGroups_CreateOrUpdate.yaml
  